server:
  port: 5678
  servlet:
    context-path: /salary

# 解决多个项目部署在tomcat报错：javax.management.InstanceAlreadyExistsException:com.zaxxer.hikari:name=mallDataSource
spring.main.allow-bean-definition-overriding: true

spring:
  freemarker:
    checkTemplateLocation: false # 关闭template目录的检查
  profiles:
    active: dev
  jmx:
    enabled: false # spring.jmx.default-domain=project1
  application:
    name: account

mybatis:
  config-location: classpath:mybatis-config.xml # mybatis配置文件所在路径


eureka:
  client:
    service-url:
      defaultZone: http://localhost:7000/eureka/
