server:
  port: 8003

mybatis:
  config-location: classpath:mybatis/mybatis-config.xml # mybatis配置文件地址

eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka/
  instance:
    instance-id: provider-log-8003 # 修改eureka上的默认描述信息
    prefer-ip-address: true  # true 可以显示服务的IP地址

spring:
  application:
    name: provider-department
  datasource:
    url: jdbc:mysql://47.92.165.44:3306/salary?useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT&allowMultiQueries=true
    username: root
    password: rpz2020.
    driver-class-name: com.mysql.cj.jdbc.Driver