server:
  port: 8004

spring:
  application:
    name: provider-menu
  datasource:
    url: jdbc:mysql://localhost:3306/salary?useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT&allowMultiQueries=true
    username: root
    password: abcABC1230.
    driver-class-name: com.mysql.cj.jdbc.Driver

eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka/

ribbon:
  eureka:
    enabled: true
