server:
  port: 81

mybatis:
  config-location: classpath:mybatis-config.xml # mybatis配置文件地址

eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka/
  instance:
    instance-id: consumer-salary-81 # 修改eureka上的默认描述信息
    prefer-ip-address: true  # true 可以显示服务的IP地址

spring:
  application:
    name: consumer-salary
  datasource:
    url: jdbc:mysql://47.92.165.44:3306/salary?useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT&allowMultiQueries=true
    username: root
    password: rpz2020.
    driver-class-name: com.mysql.cj.jdbc.Driver

ribbon:
  ConnectTimeout: 60000 # 连接超时时间(ms)
  ReadTimeout: 60000 # 通信超时时间(ms)
hystrix:
  command:
    default:
    execution:
    isolation:
    thread:
    timeoutInMilliseconds: 60000 # 设置hystrix的超时时间(ms)